# This is a minimal values.yaml that references the app-specific values repository
# Values are imported from app-01-values repo based on environment and service

# Reference configuration
valueRepo:
  # Application values repository
  name: "values-app01" 
  # Current service identifier
  service: "service-01-nginx"

# Default environment to use if not specified
defaultEnv: "dev"

# Import mechanism - automatically imports values from:
# 1. values-app01/_common.yaml (common values for all services in this app)
# 2. values-app01/service-01-nginx/values.yaml (service-specific values)
# 3. values-app01/service-01-nginx/values-{environment}.yaml (environment-specific values)

# Minimal configuration for local development/testing
# These values will be overridden by imported values
replicaCount: 1

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

# Basic service configuration
service:
  type: ClusterIP
  port: 80